StudentCouncil/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudentCouncil.Data;
using StudentCouncil.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore.Query;

namespace StudentCouncil.Controllers
{
    public class BlogController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHostingEnvironment _hostingEnvironment;

        private const int PostsPerPage = 3;

        public BlogController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            _userManager = userManager;
            _hostingEnvironment = hostingEnvironment;
        }

        // GET: BlogPosts
        public IActionResult Index(int page = 1)
        {
            IQueryable<BlogPost> BlogDBContext;

            if (page < 1)
            {
                return BadRequest();
            }

            if (!User.IsInRole("Editor"))
            {
                BlogDBContext = _context.BlogPosts.Where(post => post.Hidden == false && post.PostDateTime <= DateTime.Now);
            }
            else
            {
                BlogDBContext = _context.BlogPosts;
            }
            ViewData["NextPage"] = BlogDBContext.Count() > page * PostsPerPage;
            ViewData["NumPages"] = (BlogDBContext.Count() - 1) / PostsPerPage + 1;
            ViewData["PrevPage"] = page > 1;
            ViewData["Page"] = page;

            BlogDBContext = BlogDBContext.Include(b => b.Author).OrderByDescending(Post => Post.PostDateTime).Skip((page - 1) * PostsPerPage).Take(PostsPerPage);

            if (BlogDBContext.Count() < 1)
            {
                return NotFound();
            }

            return View(BlogDBContext);
        }

        // GET: BlogPosts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            IQueryable<BlogPost> BlogDBContext = _context.BlogPosts.Include(b => b.Author);

            if (!User.IsInRole("Editor"))
            {
                BlogDBContext = BlogDBContext.Where(post => post.Hidden == false && post.PostDateTime <= DateTime.Now);
            }
            BlogDBContext = BlogDBContext.OrderByDescending(Post => Post.PostDateTime);

            var blogPost = await BlogDBContext.SingleOrDefaultAsync(m => m.ID == id);
            if (blogPost == null)
            {
                return NotFound();
            }

            var PostList = BlogDBContext.ToList();
            var nextPostID = PostList.TakeWhile(post => post.ID != blogPost.ID);
            if (nextPostID.Count() > 0)
            {
                ViewData["NextID"] = nextPostID.Last().ID;
            }
            var prevPostID = PostList.SkipWhile(post => post.ID != blogPost.ID);
            if (prevPostID.Count() > 1)
            {
                ViewData["PrevID"] = prevPostID.Skip(1).First().ID;
            }


            if (!User.IsInRole("Editor"))
            {
                if (blogPost.Hidden || blogPost.PostDateTime > DateTime.Now) return NotFound();
            }

            return View(blogPost);
        }

        // GET: BlogPosts/Create
        [Authorize(Roles = "Editor")]
        public async Task<IActionResult> Create()
        {
            ViewData["AuthorID"] = new SelectList(await _userManager.GetUsersInRoleAsync("Student_Council_Member"), "Id", "Google_displayName", (await _userManager.GetUserAsync(User)).Id);
            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Editor")]
        public async Task<IActionResult> Create([Bind("ID,Image,Title,AuthorID,PostDateTime,Content,Hidden")] BlogPost blogPost)
        {
            if (ModelState.IsValid)
            {

                _context.Add(blogPost);
                await _context.SaveChangesAsync();

                if (blogPost.Image.Length > 0)
                {
                    using (var stream = new FileStream($"{_hostingEnvironment.WebRootPath}\\images\\Blog\\" + blogPost.ID + ".png", FileMode.Create))
                    {
                        await blogPost.Image.CopyToAsync(stream);
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorID"] = new SelectList(await _userManager.GetUsersInRoleAsync("Student_Council_Member"), "Id", "Google_displayName", (await _userManager.GetUserAsync(User)).Id);
            return View(blogPost);
        }

        // GET: BlogPosts/Edit/5
        [Authorize(Roles = "Editor")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogPost = await _context.BlogPosts.SingleOrDefaultAsync(m => m.ID == id);
            if (blogPost == null)
            {
                return NotFound();
            }
            ViewData["AuthorID"] = new SelectList(await _userManager.GetUsersInRoleAsync("Student_Council_Member"), "Id", "Google_displayName", (await _userManager.GetUserAsync(User)).Id);
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Editor")]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Title,AuthorID,PostDateTime,Content,Hidden,Image")] BlogPost blogPost)
        {
            if (id != blogPost.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(blogPost);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogPostExists(blogPost.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                if (blogPost.Image != null)
                {
                    if (blogPost.Image.Length > 0)
                    {
                        using (var stream = new FileStream($"{_hostingEnvironment.WebRootPath}\\images\\Blog\\" + blogPost.ID + ".png", FileMode.Create))
                        {
                            await blogPost.Image.CopyToAsync(stream);
                        }
                    }
                }


                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorID"] = new SelectList(await _userManager.GetUsersInRoleAsync("Student_Council_Member"), "Id", "Google_displayName", (await _userManager.GetUserAsync(User)).Id);
            return View(blogPost);
        }

        // GET: BlogPosts/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogPost = await _context.BlogPosts
                .Include(b => b.Author)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (blogPost == null)
            {
                return NotFound();
            }

            return View(blogPost);
        }

        // POST: BlogPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blogPost = await _context.BlogPosts.SingleOrDefaultAsync(m => m.ID == id);

            new FileInfo($"{_hostingEnvironment.WebRootPath}\\images\\Blog\\" + blogPost.ID + ".png").Delete();

            _context.BlogPosts.Remove(blogPost);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogPostExists(int id)
        {
            return _context.BlogPosts.Any(e => e.ID == id);
        }
    }
}

StudentCouncil/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StudentCouncil.Data;
using StudentCouncil.Models;
using StudentCouncil.Models.ShoppingCartViewModels;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace StudentCouncil.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ShoppingCart _shoppingCart;
        //Constructor
        public ShoppingCartController(ApplicationDbContext context, ShoppingCart shoppingCart)
        {
            _context = context;
            _shoppingCart = shoppingCart;
        }

        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var scvm = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(scvm);
        }
        [Authorize]
        //View to confirm adding a item - Tian
        public RedirectToActionResult AddToShoppingCart(int ID)
        {
            var selectedProduct = _context.Products.FirstOrDefault(p => p.ID == ID);
            if(selectedProduct != null)
            {

                _shoppingCart.AddToCart(selectedProduct, 1);
            }
            return RedirectToAction("Index");
        }
        //View to confirm removing an item - Tian
        public RedirectToActionResult RemoveFromShoppingCart(int ID)
        {
            var selectedProduct = _context.Products.FirstOrDefault(p => p.ID == ID);
            if(selectedProduct != null)
            {
                _shoppingCart.RemoveFromCart(selectedProduct);
            }
            return RedirectToAction("Index");
           
        }
    }
}

StudentCouncil/Controllers/SubscriptionObjectsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StudentCouncil.Data;
using StudentCouncil.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Stripe;

namespace StudentCouncil.Controllers
{
    public class SubscriptionObjectsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public SubscriptionObjectsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }

        // GET: SubscriptionObjects
        public IActionResult Index()
        {
            return View(/*await _context.SubscriptionObject.ToListAsync()*/);
        }


        public IActionResult SetSubscription(SubscriptionObject subscribe, string stripeToken)
        {
            var sub = new SubscriptionObject
            {
                Id = subscribe.Id,
                StudentId = _userManager.GetUserId(User),
                DateExpire = DateTime.Now.AddYears(1),
                // For testing purposes comment the above line of code, and uncomment the below code.
                //DateExpire = DateTime.Now.AddMinutes(1),
                Subscribed = true
            };
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            _context.SubscriptionObject.Add(sub);
            _context.SaveChanges();


            var customers = new StripeCustomerService();
            var charges = new StripeChargeService();

            var customer = customers.Create(new StripeCustomerCreateOptions
            {
                Email = User.Identity.Name,
                SourceToken = stripeToken
            });

            var charge = charges.Create(new StripeChargeCreateOptions
            {
                Amount = 1500,
                Description = "Premium Subscription",
                Currency = "nzd",
                CustomerId = customer.Id
            });

            return RedirectToAction("Index", "Product");
        }


        private bool SubscriptionObjectExists(int id)
        {
            return _context.SubscriptionObject.Any(e => e.Id == id);
        }
    }
}

StudentCouncil/Views/Shared/Charge.cshtml
<h2>Your Payment Was Successful</h2>

StudentCouncil/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  @inject SignInManager<ApplicationUser> SignInManager
  @inject UserManager<ApplicationUser> currentUser
  @*
    @model ApplicationUser<UserManager>  *@
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="author" content="Connor McCormick, Tian Dippenaar, Curtis Pritchard" />

  <!-- icon in the highest resolution we need it for -->
  <link rel="icon" sizes="192x192" href="images/logo.png">
  <link rel="apple-touch-icon" href="images/logo.png">
  <meta name="theme-color" content="#DD1122">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">

  <title>@ViewData["Title"] - Student Council</title>

  @* Styles *@
  <environment include="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet" />
    <link href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
  </environment>
  <environment exclude="Development">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
          crossorigin="anonymous"
          integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          asp-fallback-href="~/lib/font-awesome/css/font-awesome.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet" />
    <link href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.min.css" />
  </environment>

  @* Scripts *@
  <environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/popper.js/dist/umd/popper.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=dff88lf5agdz8zz744y3zq016j3ks91qfzhjv0a73gnyi9is"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
  </environment>
  <environment exclude="Development">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    <script src="~/lib/popper.js/dist/umd/popper.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1">
    </script>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=dff88lf5agdz8zz744y3zq016j3ks91qfzhjv0a73gnyi9is"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
  </environment>

  @RenderSection("Scripts", required: false)
</head>
<body onload="onLoad();">
  <div id="container">

    <!-- Navigation Area -->

    <div id="navBar" class="d-lg-none">
      <div id="navBarBurger" class="col-2" data-toggle="collapse" data-target="#navSide">
        <i class="fa fa-bars" aria-hidden="true"></i>
      </div>
      <h1 class="col-md-8 col-sm-8 col-8">MIT Student Council</h1>
      <a id="navBarLogo" class="col-2" asp-area="" asp-controller="Home" asp-action="Index">
        <img src="~/images/MIT_NoText.svg" />
      </a>
    </div>
    <div id="navSide" class="col-lg-2 col-md-4 col-sm-7 col-7 collapse show">
      <div id="navSideContent">
        <a id="sideBarLogo" class="d-none d-lg-inline" asp-area="" asp-controller="Home" asp-action="Index">
          <img src="~/images/MIT.svg" />
        </a>
        <h1 class="d-none d-lg-block">Student Council</h1><br />

        @* Navigation Options Here *@
        <ul>
          <li><a asp-area="" asp-controller="Home" asp-action="Index">Home <i class="fa fa-home" aria-hidden="true"></i></a></li>
          <li><a asp-area="" asp-controller="Home" asp-action="About">About <i class="fa fa-users" aria-hidden="true"></i></a></li>
          <li><a asp-area="" asp-controller="Blog" asp-action="Index">Blog <i class="fa fa-comments" aria-hidden="true"></i></a></li>
          @await Component.InvokeAsync("CategoryMenu")
          @*Shopping Cart*@
          @await Component.InvokeAsync("ShoppingCartSummary")
          <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact <i class="fa fa-envelope" aria-hidden="true"></i></a></li>
        </ul>
        <br />
        <div class="navSideFoot ">
          @await Html.PartialAsync("_LoginPartial")
        </div>
        @* End Navigation Options*@
      </div>
    </div>

    <!-- End Navigation -->

    <div id="mainBody" class="col-lg-10 col-12 pull-right container">
      @RenderBody()
      <hr />
      <footer class="col-12">
        <p>&copy; 2017 - Manukau Institute of Technology Student Council</p>
      </footer>
    </div>
  </div>





  <div id="modal-container" class="modal fade hidden-print" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Your Subscription has Expired!</h4>
        </div>
        <div class="modal-body">
          <div class="form-horizontal">
            Would you like to renew your subscription?
            If you would select OK, otherwise, select NO
          </div>
        </div>
        <div class="modal-footer">
          <a asp-action="Index" asp-controller="SubscriptionObjects" class="btn btn-success">OK</a>
          <a class="btn btn-secondary" data-dismiss="modal">NO</a>
        </div>
      </div>
    </div>
  </div>
  

</body>
</html>

StudentCouncil/Views/Shared/_ProductSummary.cshtml
@model Product

<div class="col-12 col-sm-6 col-md-4 productSummaryContainer">
  <div class="productSummary">
    <div class="row caption">
      <h3 class="col-7 ">
        <a>
          @Model.Name
        </a>
      </h3>
      <div class="col-5 pull-right text-right">
        <h3 style="font-size: 1.25rem;">
          @Model.Price.ToString("c")
        </h3>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-lg-7">@Html.Raw(Model.Description)</div>
      <div class="col-12 col-lg-5 text-center">
        <img src="~/images/Products/@(Model.ID).png" alt="" />
      </div>
    </div>
    <div class="addToCart text-right">
        <a class="btn btn-success" id="cartButton" asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-ID="@Model.ID">Add to Cart</a>
    </div>
  </div>
</div>